version: "3"
services:
  web:
    image: hagaik
    build: .
    deploy:
      replicas: 1
    ports:
    - "9090:9090"
    depends_on:
    - mongo
  mongo:
    image: mongo
    deploy:
      replicas: 1
    ports:
    - "27017:27017"
